### ISSUE TITLE
Port existing collectors as a set of DPP plugins

### ISSUE THREAD

**Issue by pwalsh** [okfn/measure#3]
# Description

Data Package Pipelines supports custom processors, and further, [packaging a collection of processors as a plugin](https://github.com/frictionlessdata/datapackage-pipelines#plugins-and-source-descriptors). [Data Package Pipelines Fiscal](https://github.com/openspending/datapackage-pipelines-fiscal) is a plugin with a range of processors geared towards handling fiscal data. Here is [another plugin](https://github.com/OpenBudget/budgetkey-data-pipelines) targeting usage with a fiscal data platform in Israel.

We want to ship what are currently the "collectors" in the Measure POC as a setup of processors, wrapped as a plugin: `datapackage-pipelines-measure`.

I'm writing a set of tasks below based on what I expect needs to be done, but I've not dived into any details. Please review and adjust as appropriate.

The list of existing collectors is [here](https://github.com/okfn/measure-poc/tree/master/measure/collectors) (private link). Not that each collector "type" *has* a [model](https://github.com/okfn/measure-poc/tree/master/measure/models). This is a Table Schema for each type, that describes the data structure. this will be used in the pipeline to actually generate the SQL tables for you.

The reason that several collectors share the same schema is simple: certain data types get written to common tables. The end user, say a Project Manager, looks at the "social media" data, which has Facebook and Twitter and whatever else. Or, the Technical Lead looks at the "code packaging" data, which has pypi and npm data. 

So, there can be many collectors, by each has a type, and several collectors target tables for their type, not for the individual collector.

Apply this across projects: currently in the POC, each project writes data to its own Google Spreadsheet. Moving to a database, we should write all data from **common collectors** into the same tables. This makes it easier to do queries that are cross project.

# Tasks

- [x] Create a new custom processor for each collector in the Measure POC
  - [x] Take what you can from the existing collectors without much refactoring - let's see it working before we refactor too heavily
- [x] For each, make the changes needed to "dump" data, not to Google Sheets as present, but to SQL
  - This probably requires adding some additional metadata, changing the existing payload, which is "just" a collection of rows of data, to a Data Package / Data Package Resource. The pattern should become clear as you see how DPP works, but sync with @akariv as needed
- [x] For the POC, I specified some unusual handling of dates, so that day | month | year went to distinct columns in the Spreadsheet. We don't need to do this for a proper database, so some logic will change there (probably make things simpler)
- [x] Ensure that no secrets are in the codebase (there are in the POC) - everything must use env vars
- [x] Ensure the set of collectors are usable as a DPP plugin
- [x] Many of the existing tests in the POC are written in a non optimal way - there are lots of calls to live services and so on. Take what you can, and otherwise write some new tests

**Comment by pwalsh** [comment]
@brew this is a large task. I don't mind if you break it down.

**Comment by pwalsh** [comment]
@brew 

See here for some comments I made on refactoring the original code https://github.com/okfn/measure-poc/issues/61 (private link). May or may not be useful.

**Comment by brew** [comment]
Custom processors for each existing collector:

- [x] Github (#15, #16)
- [ ] Twitter
- [ ] Discourse
- [ ] Facebook
- [ ] Google Analytics
- [ ] NPM
- [ ] Pypi

**Comment by pwalsh** [comment]
@brew seeing as there is a distinct issue for the discourse collector, you can close this issue now, no?

**Comment by brew** [comment]
Yes!
