### ISSUE TITLE
Configure Redash to read from Google Spreadsheets

### ISSUE THREAD

**Issue by pwalsh** [okfn/measure#5]
# Description

In the Measure POC, we just write all the data into Google Spreadsheets, and so the manually collected and automatically collected data all resides in the same place. This is possible with storing data in Redash too, but requires some extra configuration.

# Tasks

- [ ] Understand how to configure Redash, on a per-project basis, to pull data from several Google Forms (Google Spreadsheets) per project
- [ ] Can we have a naming pattern or similar, so that all the generic forms get written into the same tables, across projects, and only custom forms get their own tables (same pattern as with automated collectors)
- [ ] Do we need to write code? Do a little requirements doc in this thread before proceeding
- [ ] Write some docs for how this works

**Comment by akariv** [comment]
I would write a pipeline to regularly pull from GS and write to the DB.
It's possible for RD to get data from GS, but performing JOINS between GS and DB data is not possible.

**Comment by brew** [comment]
Closed in favour of #22.
