### ISSUE TITLE
Add MailChimp collector

### ISSUE THREAD

**Issue by pwalsh** [okfn/measure#6]
# Description

A new pipeline (email) and processor (mailchimp), to collect metrics related to lists and campaigns.

# Tasks

- [x] Collect subscriber count
- [x] Collect unsubscriber count
- [x] Collect campaigns sent
- [x] `email` pipeline steps
- [x] `add_mailchimp_resource` processor
- [x] Tests
- [x] Update readme
- [ ] Update schema

**Comment by pwalsh** [comment]
@brew see notes here https://github.com/okfn/measure-poc/issues/7 (private link)

**Comment by brew** [comment]
Mailchimp API:

- `subscribers`: a total number collected each day from `/lists/{id}` endpoint. Historical subscribers for each month from `/lists/{id}/growth-history`.
- `subs`: the number of subscribes each day from `/lists/{id}/activity`. Historical values available by passing a `?count=` query string for the number of days into the past to request.
- `unsubs`: the number of unsubscribes each day from `/lists/{id}/activity`. Historical values available by passing a `?count=` query string for the number of days into the past to request.
